# wrangler.toml
name = "flarechatbackend"
main = "src/index.js"
compatibility_date = "2024-12-18"

# ============================================================
# D1 DATABASE BINDING
# ============================================================
[[d1_databases]]
binding = "DB"
database_name = "flarechat"
database_id = "0811f1e4-1972-474a-a070-4a1098ab8edc"
